name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install black
          rustup toolchain add nightly-2019-08-26

      - name: Lint
        run: |
          python3 -m black --diff demo
          cargo fmt -- --check
          yarn
          yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Oasis SDK
        run: |
          curl --proto '=https' --tlsv1.2 -sSL https://get.oasis.dev | python - --speedrun
          echo "::set-env name=PATH::$HOME/.local/bin::$HOME/.cargo/bin:$PATH"

      - name: Test
        run: oasis test ./services/src/bin/user_registry.rs

  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Oasis SDK
        run: |
          curl --proto '=https' --tlsv1.2 -sSL https://get.oasis.dev | python - --speedrun
          echo "::set-env name=PATH::$HOME/.local/bin::$HOME/.cargo/bin:$PATH"

      - name: Demo
        run: make demo
